title: SearchRights.org
email: danielsgriffin@berkeley.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://SearchRights.org"
twitter_username: danielsgriffin
github_username: danielsgriffin


# Build settings
theme: minima
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-gzip
  - jekyll-include-cache
  - jekyll-scholar

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

gzip:
  extensions:
    - '.html'
    - '.css'
    - '.json'
    - '.xml'

timezone: America/Los_Angeles
